[package]
name = "rust-calc-term"
version = "0.1.0"
authors = ["Phil <phil@philthompson.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
eval = "0.4.3"